---
title: "Machine Learning"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(pacman)
p_load(tidyverse)
p_load(ggplot2)
p_load(caret)
p_load(gridExtra)
theme_set(theme_minimal())
```

```{r}
p_load(kernlab)
data(spam)

str(spam)
View(spam)
```


```{r}

# Data from ISLR

p_load(ISLR)
Auto
Caravan
Carseats
College
Credit
Default
Hitters
Khan
NCI60
OJ
Portfolio
Smarket
Wage
Weekly

# Data from MASS
p_load(MASS)
Boston

# Data from base
USArrests
```

## ISLR Page 2

```{r}
str(Wage)
ggplot(Wage,
       mapping = aes(x = age, y = wage)) +
  geom_point(size  = 1,
             alpha = 0.7,
             color = "grey",
             shape = 1) +
  geom_smooth(se = FALSE)

ggplot(Wage,
       mapping = aes(x = year, y = wage)) +
  geom_point() +
  geom_smooth(method = "lm")

ggplot(Wage) +
  geom_boxplot(mapping = aes(x = education, y = wage, fill = education))


```

## ISLR Page 16

```{r}
Advertising <- read.csv("./data/Advertising.csv")

p1 <- ggplot(data = Advertising, mapping = aes(x = TV, y = sales)) +
  geom_point(color = "red", shape = 1) +
  geom_smooth(method  ="lm", se = FALSE) +
  scale_x_continuous(breaks = c(0, 50, 100, 200, 300)) +
  scale_y_continuous(breaks = seq(0, 25,5)) +
  theme(axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank()) 

p2 <- ggplot(data = Advertising, mapping = aes(x = radio, y = sales)) +
  geom_point(color = "red", shape = 1) +
  geom_smooth(method  ="lm", se = FALSE) +
  scale_y_continuous(breaks = seq(0, 25,5)) +
  theme(axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank()) 

p3 <- ggplot(data = Advertising, mapping = aes(x = newspaper, y = sales)) +
  geom_point(color = "red", shape = 1) +
  geom_smooth(method  ="lm", se = FALSE) +
  scale_x_continuous(breaks = seq(0, 100, 20)) +
  scale_y_continuous(breaks = seq(0, 25,5)) +
  theme(axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank()) 

gridExtra::grid.arrange(
    p1,
    p2,
    p3,
    nrow = 1)
```
## ISLR Page 17

```{r}
Income <- read.csv("./data/Income1.csv")
str(Income)

p1 <- ggplot(data = Income, mapping = aes(x = Education, y = Income)) +
  geom_point(color = "red") +
  scale_x_continuous(breaks = seq(10, 22, 2)) +
  scale_y_continuous(breaks = seq(20, 80, 10)) +
  theme(axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank()) 

p2 <- ggplot(data = Income, mapping = aes(x = Education, y = Income)) +
  geom_point(color = "red") +
  geom_smooth(method = "loess",
              span = 1, 
              se = FALSE) +
  scale_x_continuous(breaks = seq(10, 22, 2)) +
  scale_y_continuous(breaks = seq(20, 80, 10)) +
  theme(axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank()) 


gridExtra::grid.arrange(
    p1,
    p2,
    nrow = 1)
```
